language: node_js
node_js:
  - 14
git: 
  depth: 3
branches: 
  only: 
    - master
install:
  - yarn
script:
  - yarn test
  - yarn build
jobs:
  include: 
    - stage: test
      script: yarn test
    - stage: build
      script: yarn build
notifications:
  email:
    reciepients:
      - cdavidramirezg24@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: $HEROKU_API_KEY
  app: mercado-libre-challenge
  on:
    repo: davidra24/Prueba-Meli