language: node_js
os: windows
git: 
  depth: 3
branches: 
  only: 
    - master
install:
  - yarn
script:
  - yarn test
  - yarn build
jobs:
  include: 
    - stage: test
      script: yarn test
    - stage: build
      script: yarn build
deploy:
  provider: heroku
  skip-cleanup: true
  keep-history: true
  api_key: apiKey
  on
    repo: davidra24/Prueba-Meli